description: mnist_estimator_const
environment:
  environment_variables:
    - DET_DEBUG_TRACK_SESSION_CONFIG=True
    - DET_DEBUG_TRACK_RUN_CONFIG=True
    - DET_DEBUG_VERBOSE_CUSTOM_LOGGING=True
    - DET_DEBUG_BREAK_VISIBLE_DEVICE_LIST=False
    - DET_DEBUG_OVERWRITE_TF_CONFIG_ENVVAR_NAME=False
    - DET_DEBUG_CHECK_DEFAULT_TF_SESSION=True
    - DET_DEBUG_LOG_CALL_STACK=True
    - DET_DEBUG_LOG_CALL_STACK_USE_TRACEBACK=True
    - DET_DEBUG_LOG_CALL_STACK_CONTINUE_THROUGH_ERROR=True
hyperparameters:
  learning_rate: 1e-3
  global_batch_size: 64
  hidden_layer_1: 2500
  hidden_layer_2: 1000
  hidden_layer_3: 500
  dropout: 0.5
searcher:
  name: single
  metric: accuracy
  max_steps: 20
  smaller_is_better: false
max_restarts: 0
entrypoint: model_def:MNistTrial
